name: CSMinecraft
version: Release 1.0
main: io.github.keheck.csminecraft.CSMinecraft
authors: [Keheck]
soft-depend: [Multiverse-Core]
permissions:
  CSMinecraft.player:
    description: Erlaubt einem Spieler, die wichtigen Funktionen des Spiels zu nutzen. Für alle Spieler freigeschaltet
    default: true
  CSMinecraft.tester:
    description: Gibt einem Spieler die Möglichkeit, eine Karte zu testen, ohne auf eine volle Lobby zu warten
    default: op
    children:
      CSMinecraft.player: true
  CSMinecraft.overwatcher:
    descriptin: Erlaubt es dir, Spiele von gemeldeten Spielern zu sehen und zu entscheiden, ob der Spieler gecheatet hat
    default: op
    children:
      CSMinecraft.player: true
      CSMinecraft.tester: true
  CSMinecraft.developer:
    description: Erleubt es dir, eine neue Map zu erstellen
    default: op
    children:
      CSMinecraft.tester: true
commands:
  cshelp:
    description: Zeigt dir alle Befehle
    usage: /cshelp <seite>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  cslist:
    description: Zeigt dir alle Maps
    usage: /cslist {name}
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csbounds:
    description: Setzt die spielbare Fläche der Map
    usage: /csbounds <x1> <y1> <z1> <x2> <y2> <z2>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csspawn:
    description: Setzt den Spawnbereich des jeweiligen Teams
    usage: /csspawn [t|ct] <x1> <z1> <x2> <z2> <y>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csbomb:
    description: Setzt den Bereich des jeweiligen Bombenorts
    usage: /csbomb [a|b] <x1> <z1> <x2> <z2> <y>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csreset:
    description: Setzt die Koordinaten des jeweiligen Bereichs zurück
    usage: /csreset [Bounds|TSpawn|CTSpawn|BombA|BombB]
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csfinish:
    description: Stellt die Map fertig und gibt ihr den angegebenen Namen
    usage: /csfinish <name>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csdelete:
    description: Löscht die Map mit dem angegebenen Namen
    usage: /csdelete <name>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csjoin:
    description: Lässt dich eine Map betreten
    usage: /csjoin <name>
    permission: CSMinecraft.player
    permission-message: Du solltest diese Erlaubnis haben... melde dich beim Support
  csforcestart:
    description: Startet ein Spiel, bevor die Map voll ist. (nützlich zum testen der Map)
    usage: /csforcestart
    permission: CSMinecraft.tester
    permission-message: Du brauchst die Rechte eines Map Testers
  csforcestop:
    description: Beendet ein Spiel vorzeitig. (nützlich zum testen der Map)
    usage: /csforcestop
    permission: CSMinecraft.tester
    permission-message: Du brauchst die Rechte eines Map Testers
  csleave:
    description: Verlasse die Map in der du bist
    usage: /csleave
    permission: CSMinecraft.player
    permission-message: Du solltest diese Erlaubnis haben... melde dich beim Support
  csreload:
    description: Lädt die Config in das Plugin. Erst dann werden Änderungen wirksam
    usage: /csreload
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte