name: CSMinecraft
version: Release 1.0.1
main: io.github.keheck.csminecraft.CSMinecraft
authors: [Keheck]
permissions:
  CSMinecraft.player:
    description: Allows a player to play on maps. Available for all players
    default: true
  CSMinecraft.tester:
    description: Gives a player the ability to play test maps without waiting for a full lobby
    default: op
    children:
      CSMinecraft.player: true
  CSMinecraft.overwatcher:
    descriptin: Allows a player to view game replays and determine whether a player was cheating or not
    default: op
    children:
      CSMinecraft.player: true
      CSMinecraft.tester: true
  CSMinecraft.developer:
    description: Allows a player to create new maps
    default: op
    children:
      CSMinecraft.tester: true
commands:
  cshelp:
    description: Shows you all commands
    usage: /cshelp <seite>
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  cslist:
    description: Shows you all maps
    usage: /cslist {name}
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csbounds:
    description: Sets the main bounds of a map
    usage: /csbounds <x1> <y1> <z1> <x2> <y2> <z2>
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csspawn:
    description: Sets the spawn of the specified team
    usage: /csspawn [t|ct] <x1> <z1> <x2> <z2> <y>
    permission: CSMinecraft.developer
    permission-message: Du brauchst Developer Rechte
  csbomb:
    description: Sets the boundary of the specified bombsite
    usage: /csbomb [a|b] <x1> <z1> <x2> <z2> <y>
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csreset:
    description: Resets the specified boundary
    usage: /csreset [Bounds|TSpawn|CTSpawn|BombA|BombB]
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csfinish:
    description: Finished the map and assignes it the specified name
    usage: /csfinish <name>
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csdelete:
    description: Deletes a map with the name
    usage: /csdelete <name>
    permission: CSMinecraft.developer
    permission-message: You need developer rights
  csjoin:
    description: Let's you join a map
    usage: /csjoin <name>
    permission: CSMinecraft.player
    permission-message: You should have this permission...
  csforcestart:
    description: Starts a not-full map. (Useful for testing a map)
    usage: /csforcestart
    permission: CSMinecraft.tester
    permission-message: You need the permission of a map tester
  csforcestop:
    description: Ends a game early. (Useful for testing maps)
    usage: /csforcestop
    permission: CSMinecraft.tester
    permission-message: You need the permission of a map tester
  csleave:
    description: Leve the current game
    usage: /csleave
    permission: CSMinecraft.player
    permission-message: You should have this permission...
  csreload:
    description: Reloads the config and applies config changes
    usage: /csreload
    permission: CSMinecraft.developer
    permission-message: You need developer rights